// v:10.4.11
var skimlinks_pub_id = '23773X825974';
var skimlinks_site = 'detailingworld.co.uk';
var skimwords_horizontal_distance = 80;
var skimwords_vertical_distance = 80;
var noskimwords = true;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
(function(){var Ja,Ka,C,La,ta,ua,Ma,Na,va,n,u,Oa,Pa,Qa,ca,Ra,Sa,Ta,wa,V,x,i,da,xa,Ua,Va,m,L,D,W,J,ea,X,k,M,N,y,p,G,ya,B,za,O,Wa,Xa,fa,Y,Ya,P,Za,$a,r,ab,bb,Aa,ga,cb,db,eb,fb,gb,hb,ib,l,jb,kb,ha,lb,mb,nb,Ba,ob,pb,qb,ia,z,rb,Ca,A,sb,ja,ka,la,Z,$,tb,Q,R,Da,ma,H,na,oa,S,T,v,U,ub,vb,wb,Ea,xb,yb,Fa,pa,Ga,w,s,aa,E,qa,ra,ba,I,Ha,K,F,Ia,zb,e,sa={}.hasOwnProperty,Ab=[].indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(b in this&&this[b]===a)return b;return-1};J=ea=null;p={pag:"",pub:"",guid:"",uc:"",
lnks:{}};k={pag:"",phr:{},pub:"",slc:0,swc:0,jsl:0,jsf:"",guid:"",uc:"",t:1};X=/http:/g;m=function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}();O=[];ya=(new Date).getTime();G=[];za=[];B=D=null;W=!1;M=[];L=[];N=[];y={"amazon.co.uk":{country:"gb",regex:[/\/(dp|product)\/([A-Z0-9]+)[\/|\?|$]?/],
search:[/keywords=([^&]+)/,/search\-alias=([^&]+)/]},"amazon.de":{country:"de",regex:[/\/(dp|product)\/([A-Z0-9]+)[\/|\?|$]?/],search:[/keywords=([^&]+)/,/search\-alias=([^&]+)/]}};T=S=na=$=Z=H=v=null;ka=[];Q=oa=ja=la=ma=null;R=!1;Da="beginning";ra=ba=qa=I=null;w="";E=s=0;aa=Ga=Ha=!1;e=this;K=e.location;F="";C=!1;Ja=["noskim","norewrite"];Ka="*.g.doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");tb=function(){return!0};
Wa=function(a){var b;b=document.createElement("a");b.href=a;return U(b.hostname)};Ma=function(){var a,b,c,d,f,g,h,j,o,t,n,i,q,l,m,r,u,w,x,y,z,A,B,C,D,G;ea=null!=(a=document.getElementsByTagName("html"))?a[0]:void 0;M=null!=(b=e.skimlinks_included_classes)?b:[];L=null!=(q=e.skimlinks_excluded_classes)?q:[];N=null!=(y=e.skimlinks_included_ids)?y:[];J=e.force_location?Wa(e.force_location):K.hostname;v=null!=(z=e.skimlinks_tracking)?z:!1;H=e.skimlinks_site||e.skimlinks_sitename||!1;Z=null!=(A=e.skimlinks_domain)?
A:"go.redirectingat.com";$=null!=(B=e.skimlinks_google)?B:!1;na=null!=$?$:"skimout";S=null!=(C=e.skimlinks_target)?C:!1;T=null!=(D=e.sl_test)?D:!1;ka=null!=(G=e.skimlinks_exclude)?G:[];ma=null!=(c=e.skimlinks_noright)?c:!1;la=null!=(d=e.skimlinks_exrel)?d:!1;ja=null!=(f=e.skimlinks_byrel)?f:!1;oa=null!=(g=e.skimlinks_blocked_tag)?g:!1;Q=0;I=null!=(h=e.skimlinks_pub_id)?h:"";if(e.skimlink_legacy_support)e.skimlinks=function(){return!0},e.mugicPopWin||(e.mugicPopWin=function(){return!0}),e.mugicRightClick||
(e.mugicRightClick=function(){return!0});s=null!=(j=e.skimlinks_dnt)?j:0;E=null!=(o=window.skimlinks_nocookie)?o:!1;E=null!=(t=window.skimlinks_nocookie)?t:!1;qa=null!=(n=e.noimpressions)?n:!1;ra=null!=(i=e.noskimlinks||e.noskim)?i:!1;ba=null!=(l=e.noskimwords||e.noskim)?l:!1;Ha=null!=(m=e.skim_toolbar)?m:!1;Ga=null!=(r=e.skimlinks_ajax_rerun)?r:!1;aa=null!=(u=e.skimlinks_ipc)?u:!1;R=null!=(w=e.skimlinks_ipc_decoration)?w:!1;Da=null!=(x=e.skimlinks_ipc_position)?x:"beginning";if(e.document&&e.document.referrer)F=
e.document.referrer;gb(J)&&(ba=ra=!0);v&&!/^[a-z0-9_\\|]+$/i.test(v)&&(v=!1);p.pag=k.pag=e.force_location||K.href;p.pub=k.pub=I;p.uc=k.uc=v;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();L.push("noskimlinks");return!0};gb=function(a){var b,c,d,f;if(e.noskim_domains){f=e.noskim_domains;for(c=0,d=f.length;c<d;c++)if(b=f[c],-1!==a.toLowerCase().indexOf(b.toLowerCase()))return!0}return!1};U=function(){var a;a=/^www\./i;return function(b){return b.replace(a,
"")}}();u=function(){return document.addEventListener?function(a,b,c){if(a&&(a.nodeName||a===e))return a.addEventListener(b,c,!1)}:function(a,b,c){if(a&&(a.nodeName||a===e))return a.attachEvent("on"+b,function(){return 7>m.version&&!window.event?(setTimeout(function(){return c.call(a,window.event)},100),!0):c.call(a,window.event)})}}();(function(){return document.createElement("div").getElementsByClassName?function(a,b){return r(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=wa(b);return xa(a,
c)}})();i=function(){var a,b;b=[function(){var b,d,f,g;f=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];g=[];for(b=0,d=f.length;b<d;b++)a=f[b],g.push([RegExp(a[0],"g"),a[1]]);return g}()];return function(c){var d,f,c=encodeURIComponent(c);for(d=0,f=b.length;d<f;d++)a=b[d],c=c.replace(a[0],a[1]);return c}}();eb=function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||!J||-1===c.indexOf(J))&&(!J||-1===J.indexOf("."+c))}}();n=
function(a,b,c){var d;3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{return d=a[b],null==d&&(d=a.getAttribute(b)),d}catch(f){return null}};x=function(a,b,c){arguments[1]="data-"+b;return n.apply(this,arguments)};vb=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)"undefined"!==typeof a.innerText?a.innerText=b:a.textContent=b,c=b;return c};pa=function(){var a,b;if(String.prototype.trim)return function(a){return null===a?
"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}();La=function(a,b){return!r(a,b)?(a.className+=" "+b,!0):!1};jb=function(a){var b,c,d,f,g;if("object"===typeof a||a instanceof Array){f="";d=0;c=a instanceof Array;for(g in a)sa.call(a,g)&&(b=a[g],0<d&&(f+=","),c?f+=l(b):(b=l(b),f+='"'+g+'":'+b),d++);return c?"["+f+"]":"{"+f+"}"}return"string"===typeof a?(b=a.replace(/"/g,
'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};l=function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify&&'["la"]'===JSON.stringify(["la"])?(a=JSON.stringify,function(b){return a(b)}):jb}();da=function(){var a,b;a=/[-[\]{}()*+?.,\\^$|#\s]/g;b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"s+")}}();wa=function(a){a=da(a);return RegExp("\\b"+a+"\\b","i")};r=function(a,b){return a.className?wa(b).test(a.className):!1};xa=function(a,b){var c,d,f,g,e;d=[];a.className&&
b.test(a.className)&&d.push(a);e=a.childNodes;for(f=0,g=e.length;f<g;f++)c=e[f],d=d.concat(xa(c,b));return d};Ra=function(a){return-1!==encodeURIComponent(a).indexOf("%C3%82%C2%A3")};Va=function(a){a=a.innerHTML.slice(0,4);if("http"===a||"www."===a)a.innerHTML="<span style='display:none!important;'> </span>";return!0};hb=function(a){for(var b,c,d,f,a=a.parentNode;a&&a!==ea;){c=a.id;for(d=0,f=M.length;d<f;d++)if(b=M[d],r(a,b))return!1;for(d=0,f=N.length;d<f;d++)if(b=N[d],c===b)return!1;for(c=
0,d=L.length;c<d;c++)if(b=L[c],r(a,b))return!0;a=a.parentNode}return M.length||N.length?!0:!1};cb=function(a,b,c){null==c&&(c=!1);for(b=RegExp("\\b(?:(?:"+da(b)+")|(?:noskim))\\b","i");null!=a&&a!==ea;){if(a.className&&b.test(a.className))return!0;a=c?null:a.parentNode}return!1};Sa=function(a,b){var c,d,f,g,h;g=F?"&pref="+i(F):"";r(a,"skimwords-link")||r(a,"skimwords-unlinked")?(h=r(a,"skimwords-link")?n(a,"data-skimwords-word"):"url",c=n(a,"data-skim-creative"),d=n(a,"data-skim-product"),f=e.skimlinks_domain||
"go.redirectingat.com","undefined"!==typeof settings&&null!==settings&&(f=settings.sw_domain||f),b="//"+f+"/?id="+I+""+(v?"&xcust="+v:"")+"&xs=2&url="+i(b)+"&xguid="+w+"&xword="+(h?h:"")+"&xcreo="+(c?c:"")+"&xpid="+(d?d:"")+"&sref="+i(K)+""+g+""+(s?"&dnt="+s:"")+""+(E?"&fdnt=1":"")):r(a,"skimlinks-inline")?(c=n(a,"data-skim-creative"),b="//"+Z+"/?id="+I+""+(H?"&site="+H:"")+""+(T?"&test="+T:"")+""+(v?"&xcust="+v:"")+"&xs=8&url="+i(b)+"&xguid="+w+"&xcreo="+(a&&null!=c?c:0)+"&sref="+i(K)+"&pref="+i(F)+
""+(s?"&dnt="+s:"")+""+(E?"&fdnt=1":"")):cb(a,"noskimlinks")||(c=n(a,"data-skim-creative"),b="//"+Z+"/?id="+I+""+(H?"&site="+H:"")+""+(T?"&test="+T:"")+""+(v?"&xcust="+v:"")+"&xs=1&url="+i(b)+"&xguid="+w+"&xcreo="+(a&&null!=c?c:0)+"&sref="+i(K)+""+g+""+(s?"&dnt="+s:"")+""+(E?"&fdnt=1":""));C&&(b+="&abp=1");return b};fa=function(a){var b;if((b=a.target||a.srcElement)&&!b.href&&a.currentTarget)b=a.currentTarget;for(;b&&"A"!==b.nodeName;)b=b.parentNode;return b};z=function(a){var b;b=fa(a);pb(b);if(e.vglnk&&
r(b,"skimwords-link"))a&&a.stopPropagation?a.stopPropagation():(a=e.event,a.cancelBubble=!0);return!0};pb=function(a){var b,c,d,f,g;f="msie"===m.browser&&7>m.version?1E4:300;b=$;if(a&&a.nodeName&&"IMG"===a.nodeName)a=a.parentNode;if(a){g=a.href;c="//"+Z;if(g.length>=c.length&&g.substr(0,c.length)===c)return!0;if("msie"===m.browser&&a.childNodes.length&&3===a.childNodes[0].nodeType)d=a.innerHTML;c=Sa(a,g);b&&wb(g);x(a,"skimlinks-orig-link")||x(a,"skimlinks-orig-link",g);a.href=c;setTimeout(function(){a.href=
x(a,"skimlinks-orig-link");x(a,"skimlinks-orig-link","");if(d)a.innerHTML=d;return!0},f)}return!0};fb=function(a,b){var c,d;null==b&&(b=za);if(b)for(c in b)if(sa.call(b,c)&&(d=b[c],d===a))return!0;return!1};ib=function(a){var b,c;if(!oa)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+oa+"]").toLowerCase();c=vb(b);c=c.toLowerCase();c=pa(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};ga=function(a){return!a||ja&&a===ja||!ab(a)};ab=function(a){var b,c,d,f;D=null;if(!a)return!1;
a=a.toLowerCase();if(D)return D[a];D={};b=la?[la]:[];b=b.concat(Ja);for(c=0,d=b.length;c<d;c++)f=b[c],D[f.toLowerCase()]=!0;return D[a]};Qa=function(){var a,b,c,d;B={};H&&ka.push(H);d=ka.concat(Ka);for(b=0,c=d.length;b<c;b++)a=d[b],B[a]=a.length;return B};db=function(a){var b,c,d;null===B&&Qa();if(!a)return!1;for(b in B)if(sa.call(B,b))if(c=B[b],0===b.indexOf("*")){if(b=b.substr(1),c-=1,d=a.lastIndexOf(b),-1!==d&&d===a.length-c)return!0}else if(a===b)return!0;return!1};Aa=function(a,b){return eb(a,
b)&&!db(b)};wb=function(a){var b,c,d;b=e.pageTracker;d=e.urchinTracker;c="/"+na+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(c),!0;if(d)return d(c),!0;if(e._gaq)b=e._gaq,b.push(["_trackEvent",na,"click",a]);return!1};Ta=function(a,b){var c,d;null==a&&(a={});null==b&&(b="track.php");for(c in k)sa.call(k,c)&&(d=k[c],a[c]=d);c="//t.skimresources.com/api/"+b;d=[];s&&d.push("dnt="+s);E&&d.push("fdnt=1");C&&d.push("abp=1");d.push("data=");c+="?"+d.join("&");return c+i(l(a).replace(X,""))};
V=function(a){var b,c;c=i('},"pub"');b=Ta();null!=a&&a.length&&(a.join(i(",")),b=b.replace(c,""+a+c));return[b,b.length]};kb=function(a){var b,c,d,f,g;p.guid=w;p.pref=F;p.lnks=[];p.typ="s";b=8E3;"msie"===m.browser&&(b=2E3);c="//t.skimresources.com/api/ipc?data=";for(f=0,g=a.length;f<g;f++)d=a[f],p.lnks.push(d),d=c+i(l(p)),d.length>b&&(p.lnks=p.lnks.slice(0,-1));p.lnks.length&&(c+=i(l(p)),P(c,!1,{async:!0}));return!0};xb=function(a){var b;if(qa)return!1;p.guid=w;p.pref=F;p.lnks=a;p.typ="s";b={data:l(p)};
b=ca(b);(C||!ha("//t.skimresources.com/api/ipc",b,Fa))&&kb(a);return!0};nb=function(){return zb()};zb=function(){var a,b,c,d,f,g,e;f=(new Date).getTime()-ya;d=[];b=8E3;"msie"===m.browser&&(b=2E3);k.slc=Q;k.swc="undefined"!==typeof sw_handlers&&null!==sw_handlers?sw_handlers:0;k.jsl=f;k.guid=w;k.pref=F;k.phr={};a=V();a=a[1];for(c=f=0,e=O.length;f<e;c=++f)if(g=O[c],g=l(g).replace(X,""),c=i('"'+c+'":'+g),!("msie"===m.browser&&c.length>b)){a=a+c.length+3*d.length;if(a>b)a=V(d),d=a[0],P(d,!1,{async:!0}),
d=[],k.t=0,a=V(),a=a[1];d.push(c)}b=V(d)[0];"msie"===m.browser&&7>m.version&&(b=b.substring(0,4095));P(b,!1,{async:!0});return ia(1)};Fa=function(){return!0};Ea=function(){var a,b,c,d,f;if(qa)return!1;a=(new Date).getTime()-ya;k.slc=Q;k.swc="undefined"!==typeof sw_handlers&&null!==sw_handlers?sw_handlers:0;k.jsl=a;k.guid=w;k.pref=F;k.phr=O;c={};for(a=d=0,f=O.length;d<f;a=++d)b=O[a],c[""+a]=b;k.phr=c;a={data:l(k)};s&&(a.dnt=s);E&&(a.fdnt=1);a=ca(a);if(C||!ha("//t.skimresources.com/api/track.php",a,
Fa))return nb(),!0;ia(1);return!0};ia=function(a){if(10>a)return G=qb(),setTimeout(function(){return ia(a+1)},2E3*a)};qb=function(){var a,b,c,d,f,g,e;b={};d=[];c=[];for(f=0,g=G.length;f<g;f++)a=G[f],a.parentNode?c.push(a):b[a.href]=1;e=Y();for(f=0,g=e.length;f<g;f++)a=e[f],b[a.href]&&d.push(a);va(d);return d.concat(c)};yb=function(a){var b,c;c=new Date;b=c+300;a=i('{"pubcode":"'+I+'","referrer":"'+K+'","pref":"'+F+'","site":"'+H+'","url":"'+a+'","custom":"'+v+'","product":"1"}');for(P("//r.skimresources.com/api/?call=track"+
(s?"&dnt="+s:"")+(E?"&fdnt=1":"")+"&data="+a);c<b;)c=new Date;return!0};Ba=function(a){a=fa(a).href;yb(a);return!0};P=function(a,b,c){var h;var d,f,g,e,j,o=this;null==c&&(c={});d=c.charset||null;j=c.target||null;h=null!=(f=c.async)?f:!0,c=h;f=null!=j&&j.document?j.document:document;g=f.getElementsByTagName("head")[0];e=f.createElement("script");e.type="text/javascript";if(d)e.charset=d;if(b)e.onload=e.onreadystatechange=function(){var a;a=!1;return function(){var c;c=o.readyState;if(!a&&(!c||"complete"===
c||"loaded"===c))return e.onload=e.onreadystatechange=null,a=!0,b.call(j),!0}}();e.async=!1!==c;e.src=a;g.appendChild(e);return e};Y=function(a){var b,c,d,f,e;b=null;a&&(b=RegExp("\\b"+da(a)+"\\b","i"));e=[];f=document.getElementsByTagName("a");for(c=0,d=f.length;c<d;c++){a=f[c];try{a.href&&(!b||a.className&&b.test(a.className))&&e.push(a)}catch(h){}}return e};va=function(a){var b,c,d,f,e,h,j,o,t;c=M.length||N.length||L.length;f=[];for(o=0,t=a.length;o<t;o++)if(b=a[o],d=U(b.hostname),b.sl_hidden_domain&&
(d=U(b.sl_hidden_domain)),j=pa(b.href),h=n(b,"rel"),e=n(b,"onclick"),n(b,"sl-processed",1),b["sl-processed"]=1,(!c||!hb(b))&&!ib(b))if(fb(d)){if(ga(h)){S&&n(b,"target",S);if("msie"===m.browser){if(Ra(j))continue;Va(b)}null!=e&&-1!==e.toString().indexOf("return false")?u(b,"mousedown",z):u(b,"click",z);ub(b,!1);bb(b);f.push(b);ma||u(b,"contextmenu",z);tb(b)}}else Aa(j,d)&&ga(h)&&(S&&n(b,"target",S),u(b,"click",Ba),ma||u(b,"contextmenu",Ba));return f};bb=function(a,b){var c,d,f,g,h,j,o,t,i;if(e.link_icon||
0<a.getAttribute("data-skim-product")&&e.skimwords_product_icon){if(0<a.getElementsByTagName("img").length)return!0;if("msie"===m.browser&&8>m.version)a.style.display="inline-block";g=d="";null!=b&&(d=e.skimwords_icon_class||"",g=e.skimwords_icon_link_class||"");h=n(a,"title").replace("'","'");f=e.link_icon||e.skimwords_product_icon;r(a,"skimwords-unlinked")||r(a,"skimwords-link")?(j='data-skim-creative="'+x(a,"skim-creative")+'"',o='data-group-id="'+x(a,"group-id")+'"',i='data-skimwords-word="'+
x(a,"skimwords-word")+'"',t='data-skimwords-id="'+x(a,"skimwords-id")+'"',c=r(a,"skimwords-unlinked")?"skimwords-unlinked":"skimwords-link"):c=t=i=o=j="";c="<a href='../Porsche 968 Nanolex Treatment (plus a few other bits....) - Detailing World_files/"+n(a,"href")+"' title='"+h+"' "+j+" "+o+" "+i+" "+t+"style='border:0px;padding:0;margin:0' class='skimlinks-icon-link "+g+" "+c+"' skimlinked='skimlinked' target='_blank'><img src='../Porsche 968 Nanolex Treatment (plus a few other bits....) - Detailing World_files/"+f+"' class='"+d+"' skimlinked='skimlinked' style='margin: 0px 0px -3px 2px !important; float:none !important;  border:0px; float:none !important; display:inline !important; width: auto !important; height: auto !important;' /></a>";
d=document.createElement("div");d.innerHTML=c;c=d.childNodes[0];u(c,"mousedown",z);a.appendChild(c)}return!0};Pa=function(a,b){var c,d;d="GBP"===a.currency?"£":"EUR"===a.currency?"€":"$";c=document.createElement("a");n(c,"href",a.url);n(c,"title",a.title);n(c,"target","_blank");La(c,"skimlinks-inline");n(c,"data-skim-creative",b);c.innerHTML=a.search?"Search on "+a.merchant:""+a.merchant+" "+d+a.price;u(c,"mousedown",z);return c};$a=function(a,b){return null!=a.currentStyle?a.currentStyle[b]:
window.getComputedStyle?document.defaultView.getComputedStyle(a,null).getPropertyValue(b):!1};Oa=function(a,b,c,d,f){return"8"+("text"===a?"1":"cross"===a?"2":"blink"===a?"3":"0")+b+c+(d-1)+f};Xa=function(a,b){var c,d,f,e,h,j,o;c=b.price;if(!c)return"0";d=0;f=1E8;h=0;for(j=0,o=a.length;j<o;j++)e=a[j],e=parseFloat(e.price),e>d&&(d=e),parseFloat(e)<f&&(f=e),e===c&&h++;return 1<h?"4":c>=d?"3":c<=f?"1":"2"};ta=function(a,b,c,d,f,e,h,j){var o,t,i,k,q,p,l,m,r,s;t=!0;k=b;i=!1;"end"===Da&&-1!==c[0].url.indexOf(j)&&
c.reverse();f.hasOwnProperty(d)?(j=f[d],e[j].cnt++):(h[d]={},j={},j.lpid=d,j.cnt=1,j.url=b.href.replace(X,""),j.prd=[],e.push(j),j=e.length-1,f[d]=j);"cross"===R?n(b,"style","text-decoration: line-through !important;"):"text"===R?null!=b.parentNode&&(f=null!=(p=$a(b.parentNode,"color"))?p:"#000",n(b,"style","color: "+f+" !important; text-decoration: none !important;")):"blink"===R&&n(b,"style","text-decoration: blink !important;");f=c.length;p=0;for(r=0,s=c.length;r<s;r++){q=c[r];i=!0;m=q.currency+
q.price+q.url+q.title+q.merchant;p+=1;o=Xa(c,q);o=Oa(R,o,f,a,p);if(!h[d].hasOwnProperty(m))l={},l.cur=q.currency,l.mn=q.merchant,l.mid=q.merchant_id,l.pr=q.price,l.ti=q.title,l.pu=q.url.replace(X,""),l.cr=o,e[j].prd.push(l),h[d][m]=!0;q=Pa(q,o);t?(m=document.createTextNode(" ("),t=!1):m=document.createTextNode(" | ");k.parentNode.insertBefore(m,k.nextSibling);m.parentNode.insertBefore(q,m.nextSibling);k=q}t||(a=document.createTextNode(") "),k.parentNode.insertBefore(a,k.nextSibling));n(b,"ipc-added",
1);return i};ob=function(a,b){var c,d,e,g,h,j,o,i,k,l,q,m;o=Y();i={};e=!1;j=[];h={};for(q=0,m=o.length;q<m;q++)c=o[q],k=n(c,"product-ref"),l=n(c,"search-term"),g=n(c,"ipc-added"),d=U(c.hostname),g||(k&&a.hasOwnProperty(k)&&ta(1,c,a[k],k,h,j,i,d)&&(e=!0),!k&&l&&b.hasOwnProperty(l)&&ta(2,c,b[l],l,h,j,i,d)&&(e=!0));if(e)return xb(j)};Ca=function(a){var b,a=null!=a?a:{};null!=e.skimlinks_runner&&(e.skimlinks_runner.skimlinks=1);b=Y();a.guid&&""===w&&(w=a.guid);if(aa)a.hasOwnProperty("products")||(a.products=
[]),a.hasOwnProperty("search_terms")||(a.search_terms=[]),ob(a.products,a.search_terms);za=a.merchant_domains;G=va(b);Q+=G.length;sb();return!0};sb=function(){"undefined"!==typeof skimwords&&null!==skimwords&&!ba?skimwords():Ea();return!0};Ya=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],(c=a.match(c))&&2<c.length)return c[2];return!1};Za=function(a,b){var c,d,e;for(d=0,e=b.length;d<e;d++)if(c=b[d],(c=a.match(c))&&1<c.length)return c[1]=decodeURIComponent(c[1]),c[1]=c[1].replace(/\+/g,
" "),c[1];return!1};Ua=function(){var a,b,c,d,e,g,h,j,o,i,k,l,m,p;e=Y();c=[];d={};j=[];o={};k=[];l={};for(m=0,p=e.length;m<p;m++)a=e[m],b=U(a.hostname),i=pa(a.href),g=n(a,"rel"),Aa(i,b)&&ga(g)&&(aa&&y.hasOwnProperty(b)&&!r(a,"skimwords-link")&&!r(a,"skimlinks-inline")&&(g=Ya(i,y[b].regex),i=Za(i,y[b].search),g&&(n(a,"product-ref",g),h=g+"|"+y[b].country,o[h]||(g={r:g,c:y[b].country,d:b},j.push(g),o[h]=!0)),i&&(n(a,"search-term",i+"|"+y[b].country),a=i+"|"+y[b].country,l[a]||(i={r:i,c:y[b].country,
d:b},k.push(i),l[a]=!0))),b&&!d[b]&&(c.push(b),d[b]=!0));return{domains:c,product_refs:j,search_terms:k}};Na=function(){var a;a=document.getElementsByTagName("body");if(0<a.length)return u(a[0],"click",ua),u(a[0],"contextmenu",ua)};ua=function(a){var b,c,d;if(e.event)a=e.event;c=a.originalTarget||a.srcElement;b=n(c,"sl-processed")||0;null==c["sl-processed"]&&(b=0);(d=n(c,"class"))&&-1!==d.indexOf("skimwords-link")&&-1!==d.indexOf("skimlinks-inline")&&(b=!0);if("A"===(null!=c?c.nodeName.toUpperCase():
void 0)&&0===b)if(a.currentTarget=c,b=fa(a),c=!0,!b||!b.href?c=!1:0!==b.href.indexOf("http://")&&0!==b.href.indexOf("https://")&&0!==b.href.indexOf("//")&&(c=!1),c)return z(a)};lb=function(a,b,c){var d,e,g,h,j,o;d=i('{"pubcode":"'+I+'","domains":_DOMAIN_LIST__PRODUCT_REFS__SEARCH_TERMS_}');h="//r.skimresources.com/api/?callback=skimlinksApplyHandlers"+(s?"&dnt="+s:"")+(E?"&fdnt=1":"")+(Ha?"&call=toolbar":"")+"&data="+d;d="msie"===m.browser?2E3:8E3;g=[];for(j=0,o=a.length;j<o;j++)e=a[j],g.push(e),
h.replace("_DOMAIN_LIST_",i(l(g))).length>d&&(g=g.slice(0,-1));h=h.replace("_DOMAIN_LIST_",i(l(g)));if(aa){a=[];for(g=0,j=b.length;g<j;g++)e=b[g],a.push(e),h.replace("_PRODUCT_REFS_",',"product_refs":'+i(l(a))).length>d&&(a=a.slice(0,-1));h=h.replace("_PRODUCT_REFS_",',"product_refs":'+i(l(a)));b=[];for(e=0,g=c.length;e<g;e++)a=c[e],b.push(a),h.replace("_SEARCH_TERMS_",',"search_terms":'+i(l(b))).length>d&&(b=b.slice(0,-1));h=h.replace("_SEARCH_TERMS_",',"search_terms":'+i(l(b)))}else h=h.replace("_PRODUCT_REFS_",
""),h=h.replace("_SEARCH_TERMS_","");return P(h)};ca=function(a){var b,c;b=[];for(c in a)a.hasOwnProperty(c)&&b.push(""+c+"="+i(a[c]));return b.join("&")};ha=function(a,b,c){var d,f,g;if("msie"!==m.browser)f=!1,g=new XMLHttpRequest,g.open("POST",a,!0),g.setRequestHeader("Content-type","application/x-www-form-urlencoded"),0<=Ab.call(g,"withCredentials")&&(g.withCredentials=!0),g.async="true",g.onreadystatechange=function(){var a;if(f)return!0;if(4===g.readyState){f=!0;if(200===g.status){a={};try{a=
JSON.parse(g.responseText)}catch(b){try{a=eval("("+g.responseText+")")}catch(d){a={}}}c(a);return!0}return!1}},g.send(b);else if(e.XDomainRequest){if(d=new XDomainRequest,0<=Ab.call(d,"withCredentials")&&(d.withCredentials=!0),d){d.open("POST",a,!0);d.onload=function(){var a;a={};if("undefined"!==typeof JSON&&null!==JSON&&JSON.parse)try{a=JSON.parse(d.responseText)}catch(b){a={}}else try{a=eval("("+d.responseText+")")}catch(e){a={}}c(a);return!0};d.onerror=function(){return!1};d.onprogress=function(){return!1};
d.ontimeout=function(){return!1};d.async=!0;try{d.send(b)}catch(h){return!1}}}else return!1;return!0};mb=function(a,b,c){var d;d={data:l({pubcode:I,domains:a,product_refs:b,search_terms:c})};d=ca(d);(C||!ha("//r.skimresources.com/api/",d,Ca))&&lb(a,b,c);return!0};Ia=function(){var a;Ma();Ga&&Na();ra?"undefined"!==typeof skimwords&&null!==skimwords&&!ba?skimwords():Ea():(a=Ua(),mb(a.domains,a.product_refs,a.search_terms));return!0};A=function(){if(W)return!1;W=!0;Bb.detect(function(a){C=a;return Ia()});
return!0};ub=function(a,b){var c,d;d=a.style.cssText;d+=" ";if(e.link_background)c=e.link_background,-1===c.indexOf("#")&&(c="#"+c),d+="background-color: "+c+" !important; ";if(null!=e.link_tooltip)a.title=e.link_tooltip;if(b){if(e.skimwords_color)c=e.skimwords_color,-1===c.indexOf("#")&&(c="#"+c),d+="color: "+c+" !important; ";e.skimwords_weight&&(d+="font-weight: "+e.skimwords_weight+" !important; ");if(e.skimwords_decoration)c=e.skimwords_decoration,d="double"===c?d+"border-bottom: 1px double !important; ":
"dashed"===c?d+"border-bottom: 1px dashed !important; ":d+("text-decoration: "+c+" !important; ");if(e.skimwords_style)c=e.skimwords_style,d+="text-style: "+c+"; ";if(e.skimwords_link_style)c=e.skimwords_link_style,d+=c+"; ";c=" "+a.className;if(e.skimwords_link_class)c+=" "+e.skimwords_link_class,a.className=c.substring(1);if(e.skimwords_title)a.title=e.skimwords_title;if(null===a.getAttribute("title"))a.title="Shopping link added by SkimWords";if(a.getAttribute("data-skim-creative")&&(c=parseInt(a.getAttribute("data-skim-creative"))%
10,1===c||2===c))a.title=""}a.style.cssText=d;return!0};rb=function(){return function(){var a,b,c;b=function(){if(W)return!0;try{document.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return A()};a=function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",a,!1);A();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",a);A();return!0}:function(){A();return!0}}();if("complete"===document.readyState)setTimeout(A,
1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),e.addEventListener("load",A,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",a);e.attachEvent("onload",A);c=!1;try{c=null===e.frameElement}catch(d){}document.documentElement.doScroll&&c&&b()}return!0}}();e.skimlinksApplyHandlers=Ca;e.mugicPopWin||(e.mugicPopWin=z);e.mugicRight||(e.mugicRight=z);e.skimlinksReload=function(){W=!1;A();return!0};e.skimlink_legacy_support||(e.skimlinks=Ia);
var Bb=new function(a){function b(a,c){e||1E3<c?"function"==typeof a&&(e?d?a(!0):a(!1):a(!1)):setTimeout(b,c*=2,a,c)}function c(){e||(g.complete&&h.complete&&(e=!0),e&&"0"!=g.width&&"0"==h.width&&(d=!0))}var d=!1,e=!1,g=null,h=null;this.detect=function(a){b(a,250)};(function(){try{var b=navigator.userAgent.toLowerCase();if(-1==b.indexOf("firefox")&&-1==b.indexOf("chrome")){e=!0;d=!1;return}}catch(i){}b=11*Math.random();g=new Image;g.onload=c;g.src=a.replace(/\*/,1).replace(/\*/,b);h=new Image;h.onload=
c;h.src=a.replace(/\*/,2).replace(/\*/,b)})()}("http://s.skimresources.com/px.gif?ch=*&rn=*");rb()})();
